import json
import re
from pathlib import Path


class ArticleService:
    """Read only the public article files generated by the site build."""

    def __init__(self, content_dir: Path) -> None:
        self.content_dir = content_dir

    async def list_articles(self) -> list[dict]:
        try:
            index = json.loads((self.content_dir / "articles.json").read_text(encoding="utf-8"))
            if index.get("version") != 1 or not isinstance(index.get("articles"), list):
                return []
            return index["articles"]
        except (OSError, ValueError, AttributeError):
            return []

    async def get_article(self, article_id: str) -> dict | None:
        # IDs originate from client metadata, so validate them before making a path.
        if not re.fullmatch(r"[\w-]+(?:/[\w-]+)*", article_id):
            return None
        catalog = await self.list_articles()
        if not any(article.get("id") == article_id for article in catalog):
            return None
        try:
            article = json.loads((self.content_dir / "articles" / f"{article_id}.json").read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return None
        return article if article.get("id") == article_id and isinstance(article.get("content"), str) else None

    async def search_articles(self, query: str) -> list[dict]:
        terms = [term.casefold() for term in re.findall(r"[\w]+", query) if len(term) >= 2]
        articles = await self.list_articles()
        if not terms:
            return []
        return [article for article in articles if any(term in " ".join(str(article.get(field, "")) for field in ("title", "description", "tags")).casefold() for term in terms)]
